services:
  db:
    image: postgres:18-alpine3.21
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - app-network

  data-service:
    build:
      context: .
      dockerfile: Dockerfile.data
    container_name: data-service
    restart: unless-stopped
    depends_on:
      - db
      - kafka
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_CHECKINS: checkins
    networks:
      - app-network

  api-service:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api-service
    restart: unless-stopped
    depends_on:
      - kafka
      - data-service
    environment:
      SERVER_PORT: 8080
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DATA_SERVICE_BASE_URL: http://data-service:8081
      KAFKA_TOPIC_CHECKINS: checkins
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
